version: '3'
services:
  bot:
    build:
        context: ./bot
        dockerfile: Dockerfile
    image: bot_image
    container_name: bot_image
    environment:
      - TOKEN=${TOKEN}
      - RM_HOST=${RM_HOST}
      - RM_USER=${RM_USER}
      - RM_PASSWORD=${RM_PASSWORD}
      - RM_PORT=${RM_PORT}

      #- CURRENT_HOST=${CURRENT_HOST}
      #- CURRENT_USER=${CURRENT_USER}
      #- CURRENT_PASSWORD=${CURRENT_PASSWORD}
      #- CURRENT_PORT=${CURRENT_PORT}

      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    depends_on:
      - db
    volumes:
      - postgres_logs:/var/log/postgresql

  db:
    build:
        context: ./db
        args:
          - DB_DATABASE=${DB_DATABASE}
          - DB_REPL_USER=${DB_REPL_USER}
          - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
          - DB_USER=${DB_USER}
          - DB_PASSWORD=${DB_PASSWORD}
        dockerfile: Dockerfile
    image: db_image
    container_name: db_image
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    command: | 
      postgres
      -c listen_addresses=*
      -c logging_collector=on
      -c log_directory='/var/log/postgresql'
      -c log_filename='logs.log'
      -c log_replication_commands=on
      -c wal_log_hints=on
      -c wal_level=replica 
      -c hot_standby=on 
      -c max_wal_senders=10 
      -c max_replication_slots=10 
      -c hot_standby_feedback=on
      -c log_min_messages=warning
      -c log_min_error_statement=error
    ports:
      - "5432:5432"
    volumes:
      - postgres_logs:/var/log/postgresql

  db_repl:
    build:
        context: ./db_repl
        dockerfile: Dockerfile
    image: db_repl_image
    container_name: db_repl_image
    environment:
      - POSTGRES_USER=${DB_REPL_USER}
      - POSTGRES_PASSWORD=${DB_REPL_PASSWORD}
      - PGUSER=${DB_REPL_USER}
      - PGPASSWORD=${DB_REPL_PASSWORD}
    volumes:
      - db_repl_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    depends_on:
      - db
    command: |
      bash -c "
      rm -rf /var/lib/postgresql/data/*
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --username=\${DB_REPL_USER} --host=db --port=5432
      do
        echo 'Waiting for primary to connect...'
        sleep 1s
      done
      echo 'Backup done, starting replica...'
      chown -R postgres:postgres /var/lib/postgresql/data
      chmod 0700 /var/lib/postgresql/data
      su - postgres -c '/usr/lib/postgresql/16/bin/postgres -D /var/lib/postgresql/data'
      "

volumes:
  postgres_logs:
  db_repl_data:
